version: '3.3'

# mongodb v5 and later requires certain intel cpu features only present in recent models

services:
  dogpile-mongodb-cache:
    container_name: dogpile-mongodb-cache
    image: mongo:4.4.22
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "rootpw"
      MONGO_INITDB_DATABASE: "dogpile_work"
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
